int select_rr_weight (struct multipath * mp);
int select_pgfailback (struct multipath * mp);
int select_pgpolicy (struct multipath * mp);
int select_selector (struct multipath * mp);
int select_alias (struct multipath * mp);
int select_features (struct multipath * mp);
int select_hwhandler (struct multipath * mp);
int select_checker(struct path *pp);
int select_getuid (struct path * pp);
int select_prio (struct path * pp);
int select_no_path_retry(struct multipath *mp);
int select_pg_timeout(struct multipath *mp);
int select_flush_on_last_del(struct multipath *mp);
int select_minio(struct multipath *mp);
int select_mode(struct multipath *mp);
int select_uid(struct multipath *mp);
int select_gid(struct multipath *mp);
int select_fast_io_fail(struct multipath *mp);
int select_dev_loss(struct multipath *mp);
int select_reservation_key(struct multipath *mp);
int select_retain_hwhandler (struct multipath * mp);
int select_detect_prio(struct path * pp);
int select_detect_checker(struct path * pp);
int select_deferred_remove(struct multipath *mp);
int select_delay_watch_checks (struct multipath * mp);
int select_delay_wait_checks (struct multipath * mp);
int select_marginal_path_err_sample_time(struct multipath *mp);
int select_marginal_path_err_rate_threshold(struct multipath *mp);
int select_marginal_path_err_recheck_gap_time(struct multipath *mp);
int select_marginal_path_double_failed_time(struct multipath *mp);
int select_skip_kpartx (struct multipath * mp);
int select_max_sectors_kb (struct multipath * mp);
int select_unpriv_sgio (struct multipath * mp);
int select_ghost_delay (struct multipath * mp);
int select_all_tg_pt (struct multipath *mp);
